// <auto-generated />
namespace ChattingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Photo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Photo));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050811068_Photo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
